name: lingularity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0.2
  - mypy=0.770
  - matplotlib=3.2.1
  - numpy=1.18.1
  - unidecode=1.1.1
  - requests=2.23.0
  - tqdm=4.45.0
  - nltk=3.4.5
  - pip:
    - bs4==0.0.1
