name: backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0.2
  - pytest  # dev
  - mypy  # dev
  - numpy=1.18.1  # one application
  - requests=2.23.0  # dev
  - unidecode=1.1.1
  - nltk=3.4.5
  - pymongo=3.9.0
  - tqdm
  - requests
  - pip:
    - dnspython
    - playsound
    - cryptography==3.1  # one application
    - gTTS  # dev
    - textacy
    - spacy
    - coverage  # dev
    - monostate
    - types-requests  # dev
