name: lingularity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - pyinstaller
  - unidecode=1.1.1
  - requests=2.23.0
  - tqdm
  pip:
    - bs4==0.0.1
